### PR TITLE
Minor semantics change in database summary

### PR DESCRIPTION
**Pull request by rmmiller22**
Changed SAV to missense to more accurately reflect the category. There are missense mutations that we observe that involve more than a single amino acid. This change will also be reflected in the MetaMorpheus variant summary output.

### CODE REVIEW

**Comment by acesnik** [comment]
Let's separate SNV missense and MNV missense to emphasize that we can find MNV ones, which are kind of new to proteogenomics. I'll make that change in SpritzSnake in an upcoming pull request. Do you want to make the corresponding change in MM?

**Comment by acesnik** [comment]
```
                    else if (culture.CompareInfo.IndexOf(variant.Description.Description, "missense_variant", CompareOptions.IgnoreCase) >= 0 &&
                        variant.Description.ReferenceAlleleString.Length == 1 && variant.Description.AlternateAlleleString.Length == 1)
                    {
                        missenseSnvCount++;
                        totalVariants++;
                    }
                    else if (culture.CompareInfo.IndexOf(variant.Description.Description, "missense_variant", CompareOptions.IgnoreCase) >= 0)
                    {
                        missenseMnvCount++;
                        totalVariants++;
                    }
```

**Comment by rmmiller22** [comment]
That is an awesome idea, so much better then having to filter after the fact. I can definitely integrate that into MM.

**Comment by acesnik** [comment]
Awesome, thank you!

**Pull request merged**
